### ISSUE TITLE
Looper 5 timing (from VCV forum)

### ISSUE THREAD

**Issue by armandvedel** [sickozell/SickoCV#11]
I'm writing this issue here, I think it's better here than in the forum. I tested this for a couple hours and it seems inconsistent to me.

I am trying to get Looper5 to start in sync with an external clock. I see an issue about external clock has been posted before, but for me it's slightly different.

I have no problems recording a 2 measure loop with an external clock

What I expect to happen after recording, is that when I reset the looper and the clock, and then start the clock again, the loops will start immediately. In reality, sometimes this happens, but sometimes it takes one bar, as if there is a count-in. (count in is turned off).  The click output is bang on and works reliably, so I don't understand why the loop doesn't start in time with the click every time.

One way I have gotten this to work is by pressing start/stop (all start stop on the right side of the panel). When I start the external clock, the meters start to evolve green, then turn idle blue after a short while. Then if I stop, and again press play on the individual tracks, the button blinks, indicating the tracks are ready. Then I reset again and start the clock, and they will start immediately every time.

Anyway I assume this is not how it is supposed to work, so I will just provide this feedback for now.

**Comment by sickozell** [comment]
Thanks for posting your issue here, it may be useful for the future.  
When using external clock sickoLooper can't determine which clock pulse is the first of the measure, because it starts counting on the first received clock, and it will count clocks according to meter settings. The "External Clock Reset" is used to reset this counter.  
Using triggers to start/stop loops in sync with other patch elements may be tricky (be careful to the 1 sample delay between modules), and may need the use of clock dividers, buffered triggers or even leaving sickoLooper unsynced.  
However, the several options of sickoLooper are quite flexible to achieve the expected results.
