### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by CarlosBoix** [sickozell/SickoCV#9]
Hey hope all is well,

Whilst using polymuter8+ I thought it would be neat to be able to use the solo function and reduce the polyphonic cables accordingly, so if one solos 1 channel polyphony is reduced to 1 and if one solos 2 channels then you have only 2 polyphonic signals in the cable. Same for muting. 

Currently when one mutes the voltage drops to 0 but the channel is still carried as 0v so on an oscillator you get a pitch output. 

Would it be possible to implement ?

**Comment by sickozell** [comment]
Published v2.6.15-beta1 in the releases area with polyMuter8+ and Polymuter16+ updates.  
Please report me any issue or suggestions.  
If it's working fine, polyMuter8 and polyMuter16 could be updated too

**Comment by CarlosBoix** [comment]
Hey, thanks a lot for doing this so quickly !

When I drop the plug in in the folder i get this update notice which seems odd as it seems a downgrde ?

Am I doing something wrong ?

<img width="205" alt="Screenshot 2024-07-24 at 18 35 21" src="https://github.com/user-attachments/assets/cbe5a45f-667c-483a-9c4a-43be1ffebb5e">

**Comment by CarlosBoix** [comment]
I've downloaded arm64 vwersion

![image](https://github.com/user-attachments/assets/1c6c0483-71d5-4544-af05-9771a67d4f18)

**Comment by sickozell** [comment]
It's allright. Vcv would like to update to last official release, just ignore that

**Comment by CarlosBoix** [comment]
All working smoothly on PM8+ after a few days of testing. Thank you for implementing this so quickly

**Comment by CarlosBoix** [comment]
Would it be too much to ask that you add another feature to the module  ? I would really like it if it could filter out any -10V automatically shrinking those signals out of the poly out. So in the example below, auto mute or ignore ch 11 to 14
![Screenshot 2024-08-01 at 11 25 00](https://github.com/user-attachments/assets/2dbcfa98-b490-4c22-9256-6c68f21d3789)

**Comment by sickozell** [comment]
Due to the architecture of the polyMute, such functionality would create conflicts.  
I suggest the alternative of using mute button mapping with uMap to achieve automatic mute.  
In the example below you can mute channels by applying a gate on uMap modules.
![Cattura](https://github.com/user-attachments/assets/c7a6dac2-e954-4e96-8d33-bf79b266a26f)

**Comment by sickozell** [comment]
Since it was simplier, I added your feature request of muting channels with -10 voltages in the pM8 and pM16 modules.  
Can you try them and report me how they work?  
I added also a 'Show OUT channels' menu option to monitor the output.  
![image](https://github.com/user-attachments/assets/90ed552c-e143-4c4a-8b44-9f86f715d6a9)

**Comment by CarlosBoix** [comment]
Wow just tried it and it works like a dream  ! Gone above and beyond man. Thank you so much for this.

Would you be interested in collaborating in making a bespoke module to make colundi music ? We have been looking for someone with your skills and passion for a very long time

**Comment by sickozell** [comment]
Very good. I will submit this version to the library.  
I dm you on vcv community forum
